version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

workflows:
  test-ci:
    jobs:
      - build-and-test
      # - build-and-push-to-dockerhub
  build-and-push-and-deploy:
    jobs:
      - build-and-test
      - build-and-push-to-dockerhub:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy-to-heroku:
          requires:
            - build-and-push-to-dockerhub
          filters:
            branches:
              only: master

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8

    environment:
      SENTRY_KEY: $SENTRY_KEY


  build-and-push-to-dockerhub:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_SHA1
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker build -t python-oc-lettings-fr:$TAG .
          docker tag python-oc-lettings-fr:$TAG $DOCKERHUB_USERNAME/python-oc-lettings-fr:$TAG
          docker push $DOCKERHUB_USERNAME/python-oc-lettings-fr:$TAG

    environment:
      SENTRY_KEY: $SENTRY_KEY

  deploy-to-heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Push to heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web

    environment:
      SENTRY_KEY: $SENTRY_KEY