version: 2.1

orbs:
  python: circleci/python@1.5.0

workflows:
  test-ci:
    jobs:
      - build-and-test
      - build-and-push-to-dockerhub

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8

  build-and-push-to-dockerhub:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_SHA1
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker build -t python-oc-lettings-fr:$TAG .
          docker tag python-oc-lettings-fr:$TAG $DOCKERHUB_USERNAME/python-oc-lettings-fr:$TAG
          docker push $DOCKERHUB_USERNAME/python-oc-lettings-fr:$TAG