version: 2.1

workflows:
  test-ci:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8

