# Generated by Django 3.0 on 2023-02-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20230214_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
